backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: main # Branch to update
  repo: nerohoop/gatsby-blog # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: themes/advanced/content/images
public_folder: images

collections:
  - name: blog
    label: "Post"
    folder: "themes/advanced/content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publication Date", name: "datePublished", widget: "datetime" }
      - { label: "Modification Date", name: "dateModified", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Cover Image Alt", name: "coverAlt", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
